# Generated by Django 3.0.3 on 2020-05-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
                ('up_date', models.DateField()),
            ],
        ),
    ]
