# Generated by Django 3.0.3 on 2020-05-18 06:52

import MyMems.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyMems', '0003_auto_20200518_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='images',
            field=models.ImageField(default='', upload_to=MyMems.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='notes',
            field=models.FileField(default='', upload_to=MyMems.models.get_upload_path),
        ),
    ]
