# Generated by Django 3.0.3 on 2020-05-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyMems', '0004_auto_20200518_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('notesname', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=1000)),
            ],
            options={
                'unique_together': {('uname', 'time')},
            },
        ),
    ]
